name: SQL Automation with Dynamic SSH

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Pinggy Tunnel via Dynamic SSH
        run: |
          nohup ${{ secrets.PINGGY_SSH }} > pinggy_output.txt 2>&1 &
          sleep 5  # Wait for Pinggy to initialize

      - name: Extract Pinggy Port
        run: |
          PORT=$(grep -oP 'localhost:(\d+)' pinggy_output.txt | grep -oP '\d+')
          echo "PINGGY_PORT=$PORT" >> $GITHUB_ENV

      - name: Install SQLCMD tools
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo "/opt/mssql-tools/bin" >> $GITHUB_PATH

      - name: Run SQL Script
        run: |
          /opt/mssql-tools/bin/sqlcmd -S "localhost,${{ env.PINGGY_PORT }}" \
          -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} \
          -i TestQuery.sql
