name: SSIS Deployment (CMD Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: local-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SSIS DevOps Tools
        run: |
          mkdir "C:\ssis-tools"
          curl -L https://github.com/microsoft/SSIS-DevOps-Tools/releases/latest/download/SSISDevOpsTools.zip -o "C:\ssis-tools\tools.zip"
          if not exist "C:\ssis-tools\tools.zip" (
            echo "::error::Failed to download SSIS DevOps Tools!"
            exit /b 1
          )
          cd / Focusing on the root cause, the issue is that `SSISBuild.exe` is not found. Let’s prioritize verifying the tool’s presence and PATH configuration.

### Immediate Actions
1. **Check `C:\ssis-tools` on the Runner**:
   - Log into `LAPTOP-H6CGEPKT`.
   - Navigate to `C:\ssis-tools` and confirm `SSISBuild.exe` exists.
   - If not, manually download the SSIS DevOps Tools from the correct source (e.g., Microsoft’s GitHub releases) and extract to `C:\ssis-tools`.

2. **Test PATH Locally**:
   - Open a command prompt on the runner machine.
   - Run:
     ```cmd
     set PATH=%PATH%;C:\ssis-tools
     where SSISBuild.exe
