name: SSIS Deployment (CMD Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: local-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SSIS DevOps Tools
        run: |
          if not exist "C:\ssis-tools\SSISBuild.exe" (
            mkdir "C:\ssis-tools"
            curl -L <correct-URL> -o "C:\ssis-tools\tools.zip"
            if not exist "C:\ssis-tools\tools.zip" (
              echo "::error::Failed to download SSIS DevOps Tools!"
              exit /b 1
            )
            cd /d "C:\ssis-tools"
            powershell -Command "Expand-Archive -Path tools.zip -DestinationPath . -Force"
            if not exist "C:\ssis-tools\SSISBuild.exe" (
              echo "::error::SSISBuild.exe not found after extraction!"
              dir "C:\ssis-tools"
              exit /b 1
            )
            del tools.zip
          ) else (
            echo "SSIS DevOps Tools already installed in C:\ssis-tools"
          )
        shell: cmd

      - name: Add Tools to PATH
        run: |
          set "PATH=%PATH%;C:\ssis-tools"
          echo %PATH%
          where SSISBuild.exe
          if %ERRORLEVEL% neq 0 (
            echo "::error::SSISBuild.exe not found in PATH!"
            exit /b 1
          )
        shell: cmd

      - name: Validate SSIS project
        run: |
          if not exist "%GITHUB_WORKSPACE%\Timesheet\TimesheetMigrationV2.dtproj" (
            echo "::error::SSIS project file not found!"
            exit /b 1
          )
        shell: cmd

      - name: Build SSIS Package
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          SSISBuild.exe -p:Timesheet\TimesheetMigrationV2.dtproj -o:build -c:Release -l:build.log
          if not exist "Timesheet\build\Release\TimesheetMigrationV2.ispac" (
            echo "::error::Build failed!"
            type build.log || echo "No build log available"
            exit /b 1
          )
        shell: cmd

      - name: Deploy to SQL Server
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          SSISDeploy.exe -s:Timesheet\build\Release\TimesheetMigrationV2.ispac ^
            -d:CATALOG;/SSISDB/TimesheetMigrationPacks/TimesheetMigrationV2;LAPTOP-H6CGEPKT ^
            -authType:WIN ^
            -l:deploy.log
          if %ERRORLEVEL% neq 0 (
            echo "::error::Deployment failed!"
            type deploy.log || echo "No deploy log available"
            exit /b 1
          )
        shell: cmd

      - name: Verify Deployment
        run: |
          sqlcmd -S LAPTOP-H6CGEPKT -E -Q "SELECT name FROM SSISDB.catalog.projects WHERE name = 'TimesheetMigrationV2'"
          if %ERRORLEVEL% neq 0 (
            echo "::error::Verification failed!"
            exit /b 1
          )
        shell: cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifacts
          path: |
            %GITHUB_WORKSPACE%\Timesheet\build\Release\TimesheetMigrationV2.ispac
            %GITHUB_WORKSPACE%\build.log
            %GITHUB_WORKSPACE%\deploy.log
