name: SSIS Deployment (CMD Only)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: local-dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download SSIS DevOps Tools
        run: |
          mkdir "C:\ssis-tools"
          curl -L https://github.com/microsoft/SSIS-DevOps-Tools/releases/latest/download/SSISDevOpsTools.zip -o "C:\ssis-tools\tools.zip"
          cd /d "C:\ssis-tools"
          tar -xf tools.zip
          del tools.zip
        shell: cmd

      - name: Add Tools to PATH
        run: |
          set "PATH=%PATH%;C:\ssis-tools"
        shell: cmd

      - name: Validate SSIS project
        run: |
          if not exist "%GITHUB_WORKSPACE%\Timesheet\TimesheetMigrationV2.dtproj" (
            echo "::error::SSIS project file not found!"
            exit /b 1
          )
        shell: cmd

      - name: Build SSIS Package
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          SSISBuild.exe -p:Timesheet\TimesheetMigrationV2.dtproj -o:build -c:Release -l:build.log
          
          if not exist "Timesheet\build\Release\TimesheetMigrationV2.ispac" (
            echo "::error::Build failed!"
            type build.log || echo "No build log available"
            exit /b 1
          )
        shell: cmd

      - name: Deploy to SQL Server
        run: |
          cd /d "%GITHUB_WORKSPACE%"
          SSISDeploy.exe -s:Timesheet\build\Release\TimesheetMigrationV2.ispac ^
            -d:CATALOG;/SSISDB/TimesheetMigrationPacks/TimesheetMigrationV2;LAPTOP-H6CGEPKT ^
            -authType:WIN ^
            -l:deploy.log
          
          if %ERRORLEVEL% neq 0 (
            echo "::error::Deployment failed!"
            type deploy.log || echo "No deploy log available"
            exit /b 1
          )
        shell: cmd

      - name: Verify Deployment
        run: |
          sqlcmd -S LAPTOP-H6CGEPKT -E -Q "SELECT name FROM SSISDB.catalog.projects WHERE name = 'TimesheetMigrationV2'"
          if %ERRORLEVEL% neq 0 (
            echo "::error::Verification failed!"
            exit /b 1
          )
        shell: cmd

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: deployment-artifacts
          path: |
            %GITHUB_WORKSPACE%\Timesheet\build\Release\TimesheetMigrationV2.ispac
            %GITHUB_WORKSPACE%\build.log
            %GITHUB_WORKSPACE%\deploy.log
