name: Deploy SSIS Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug: Verify directory contents
      - name: List directory contents
        run: dir "${{ github.workspace }}"
        shell: cmd

      # Install SSIS DevOps Tools
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Build SSIS project to generate .ispac file
      - name: Build SSIS Project
        run: |
          cd "${{ github.workspace }}"
          SSISBuild.exe -p "Timesheet\TimesheetMigrationV2.dtproj" -c "Release" -o "build" -ss
        shell: cmd

      # Deploy .ispac file to SSIS Catalog
      - name: Deploy SSIS Package
        run: |
          SSISDeploy.exe "build\TimesheetMigrationV2.ispac" -Catalog SSISDB -Server "${{ secrets.SQL_SERVER_NAME }}" -User "${{ secrets.SQL_SERVER_USER }}" -Password "${{ secrets.SQL_SERVER_PASSWORD }}"
        shell: cmd

      # Optional: Archive the .ispac file as an artifact
      - name: Upload ISPAC Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssis-deployment-package
          path: ${{ github.workspace }}\build\TimesheetMigrationV2.ispac
