name: Deploy SSIS Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SSIS_FOLDER: "TimesheetMigrationPacks"
  SSIS_PROJECT: "TimesheetMigrationV2"

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Debug: Verify directory contents
      - name: List directory contents
        run: dir "${{ github.workspace }}"
        shell: cmd

      # Verify the .dtproj file exists
      - name: Check dtproj file
        run: if not exist "${{ github.workspace }}\Timesheet\${{ env.SSIS_PROJECT }}.dtproj" exit /b 1
        shell: cmd

      # Install SSIS DevOps Tools
      - name: Setup SSIS DevOps Tools
        uses: jonlabelle/setup-ssis-devops-tools@v1

      # Build SSIS project to generate .ispac file
      - name: Build SSIS Project
        run: |
          cd "${{ github.workspace }}"
          SSISBuild.exe `
            -p:Timesheet\${{ env.SSIS_PROJECT }}.dtproj `
            -o:build\Development `
            -ss `
            -l:INFO;build.log
        shell: powershell

      # Deploy .ispac file to SSIS Catalog
      - name: Deploy SSIS Package
        run: |
          $ispacPath = "${{ github.workspace }}\build\Development\${{ env.SSIS_PROJECT }}.ispac"
          $deployTarget = "CATALOG;/SSISDB/${{ env.SSIS_FOLDER }}/${{ env.SSIS_PROJECT }};${{ secrets.DEV_SQL_SERVER_URL }}"
          
          Write-Host "Deploying $ispacPath to $deployTarget"
          SSISDeploy.exe `
            -s:$ispacPath `
            -d:$deployTarget `
            -authType:WIN `
            -l:INFO;deploy.log
          
          if ($LASTEXITCODE -ne 0) {
              Write-Error "Deployment failed with exit code $LASTEXITCODE"
              exit $LASTEXITCODE
          }
        shell: powershell

      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ssis-artifacts
          path: |
            ${{ github.workspace }}\build\Development\${{ env.SSIS_PROJECT }}.ispac
            ${{ github.workspace }}\build.log
            ${{ github.workspace }}\deploy.log
