name: Deploy SSIS Package (Ubuntu)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Install sqlcmd and dependencies (Ubuntu)
      - name: Install SQL Server tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      # 3. Validate .ispac file exists (debugging)
      - name: Check ISPAC file
        run: |
          if [ ! -f "Timesheet/build/Development/TimesheetMigrationV2.ispac" ]; then
            echo "::error::ISPAC file not found!"
            exit 1
          else
            echo "ISPAC file found."
          fi

      # 4. Deploy using T-SQL
      - name: Deploy to SSIS Catalog
        env:
          SQL_SERVER: ${{ secrets.DEV_SQL_SERVER_URL }}
          SQL_USER: ${{ secrets.DEV_SQL_USER }}
          SQL_PASSWORD: ${{ secrets.DEV_SQL_PASSWORD }}
        run: |
          # Convert .ispac to hex
          HEX_CONTENT=$(xxd -p "Timesheet/build/Development/TimesheetMigrationV2.ispac" | tr -d '\n')

          # T-SQL deployment command
          sqlcmd -S "$SQL_SERVER" \
                 -U "$SQL_USER" \
                 -P "$SQL_PASSWORD" \
                 -d "SSISDB" \
                 -Q "
            DECLARE @project_binary VARBINARY(MAX) = 0x$HEX_CONTENT;
            BEGIN TRY
              EXEC [catalog].[deploy_project] 
                @folder_name = 'TimesheetMigrationPacks',
                @project_name = 'TimesheetMigrationV2',
                @project_stream = @project_binary;
              PRINT 'Deployment succeeded.';
            END TRY
            BEGIN CATCH
              PRINT 'Error: ' + ERROR_MESSAGE();
              THROW;
            END CATCH"

      # 5. (Optional) Upload .ispac as artifact for debugging
      - name: Upload ISPAC artifact
        uses: actions/upload-artifact@v4
        with:
          name: ssis-package
          path: Timesheet/build/Development/TimesheetMigrationV2.ispac
