name: Pinggy TCP Tunnel
on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  expose:
    runs-on: windows-latest  # Required for PowerShell
    steps:
    - name: Start Pinggy TCP tunnel
      id: pinggy
      run: |
        # Execute the Pinggy command and capture output
        $pinggyCmd = "${{ secrets.PINGGY_SSH }}"
        $output = (Invoke-Expression $pinggyCmd) 2>&1 | Out-String

        # Extract TCP endpoint (modify pattern if needed)
        $tcpUrl = $output | Select-String -Pattern 'tcp://[^\s]+' | ForEach-Object { $_.Matches.Value }
        $tcpHost, $tcpPort = $tcpUrl -replace 'tcp://','' -split ':'

        # Set outputs for other steps
        Write-Output "TCP_HOST=$tcpHost" >> $env:GITHUB_OUTPUT
        Write-Output "TCP_PORT=$tcpPort" >> $env:GITHUB_OUTPUT
        Write-Output "TCP_URL=$tcpUrl" >> $env:GITHUB_OUTPUT

        # Display in logs
        Write-Host "##[group]Pinggy Tunnel Details"
        Write-Host "TCP Endpoint: $tcpUrl"
        Write-Host "Host: $tcpHost"
        Write-Host "Port: $tcpPort"
        Write-Host "##[endgroup]"
      shell: pwsh

    - name: Display tunnel information
      run: |
        Write-Host "Your TCP tunnel is active at:"
        Write-Host "URL: ${{ steps.pinggy.outputs.TCP_URL }}"
        Write-Host "Host: ${{ steps.pinggy.outputs.TCP_HOST }}"
        Write-Host "Port: ${{ steps.pinggy.outputs.TCP_PORT }}"
      shell: pwsh
