name: Display Pinggy Tunnel Output

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner for PowerShell compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Pinggy Tunnel via PowerShell
        run: |
          Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-Command", "${{ secrets.PINGGY_SSH }} | Out-File pinggy_output.txt"
          Start-Sleep -Seconds 5  # Wait for Pinggy to initialize

      - name: Display Pinggy Tunnel Output
        run: |
          Get-Content "pinggy_output.txt" | Write-Host

