
name: Display Pinggy Tunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner for PowerShell compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Pinggy Tunnel via PowerShell
        run: |
          Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-Command", "${{ secrets.PINGGY_SSH }} | Out-File pinggy_output.txt"
          Start-Sleep -Seconds 5  # Wait for Pinggy to initialize

      - name: Extract and Display Tunnel Port
        run: |
          $port = Select-String -Path "pinggy_output.txt" -Pattern 'localhost:(\d+)' | ForEach-Object { $_.Matches.Groups[1].Value }
          if ($port) {
            Write-Host "::notice:: Tunnel Port: $port"
          } else {
            Write-Host "::error:: Failed to detect Pinggy port."
            exit 1
          }
