name: Display Pinggy Tunnel Output

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner for PowerShell compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Pinggy Tunnel via PowerShell
        run: |
          Start-Process -NoNewWindow -FilePath "powershell.exe" -ArgumentList "-Command", "${{ secrets.PINGGY_SSH }} | Out-File pinggy_output.txt"
          Start-Sleep -Seconds 5  # Wait for Pinggy to initialize

      - name: Echo Pinggy Tunnel Output as Message
        run: |
          $output = Get-Content "pinggy_output.txt" | Out-String
          Write-Host "::notice:: Pinggy Output: $output"

      - name: Save Pinggy Output as Artifact
        uses: actions/upload-artifact@v4  # Updated to v2
        with:
          name: pinggy-output
          path: pinggy_output.txt

      - name: Set Pinggy Output as Workflow Output
        id: set_output
        run: |
          echo "PINGGY_OUTPUT=$(cat pinggy_output.txt)" >> $GITHUB_ENV
