name: Display Pinggy Tunnel

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest  # Windows runner for PowerShell compatibility

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start Pinggy Tunnel and Extract Port
        run: |
          $output = & "${{ secrets.PINGGY_SSH }}"
          $port = ($output | Select-String -Pattern 'localhost:(\d+)').Matches.Groups[1].Value
          if ($port) {
            Write-Host "::notice:: Tunnel Port: $port"
          } else {
            Write-Host "::error:: Failed to detect Pinggy port."
            exit 1
          }
